name: demo_flutter_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  equatable: ^2.0.5
  lottie: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  keyboard_actions: ^4.2.0
  intl: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mockito: ^5.0.2
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/
    - assets/icons/
flutter_intl:
  enabled: true
